dist: bionic

sudo: required

language: python

python:
  - 3.6
  - 3.7
  - 3.8

before_script:
  - pip install .

script:
  - python -c "import rxn4chemistry"

deploy:
  provider: script
  skip_cleanup: true
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master$

